### ISSUE TITLE
Can't get the knowledge assistant to work

### ISSUE THREAD

**Issue by sheng-liang** [acorn-io/rubra#26]
Create a new assistant, and upload a text version of Google Q4 2023 earnings release. The resulting assistant always responds with "Sorry, I can't find any relevant information." regardless what questions I ask.

I tried uploading the original PDF version of the earnings release. It does not work either.
[2023q4-alphabet-earnings-release.pdf](https://github.com/acorn-io/rubra/files/14251802/2023q4-alphabet-earnings-release.pdf)
[2023q4-alphabet-earnings-release.txt](https://github.com/acorn-io/rubra/files/14251803/2023q4-alphabet-earnings-release.txt)

**Comment by sanjay920** [comment]
There was an encoding issue. Rubra couldn't index the earnings release due to invalid UTF-8 encoding.
I've pushed out a fix that automatically detects and applies encoding. https://github.com/acorn-io/rubra/commit/78d6e4929670edd844e7d1ec35899307d565b546

Assistant with the pdf file:
<img width="1624" alt="image" src="https://github.com/acorn-io/rubra/assets/6551215/3a528b96-7fb0-48f5-b759-69d6aff5c3a9">


Assistant with the text file:
<img width="1600" alt="image" src="https://github.com/acorn-io/rubra/assets/6551215/fd08d0a4-9401-4aa6-b355-2ea111516590">
